# Generated by Django 4.1.1 on 2022-10-02 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripción', models.CharField(help_text='Descripción del documento', max_length=80)),
                ('ruta_del_documento', models.FileField(help_text='Documento que va a mostrar el bot con algún comando vinculado', upload_to='upload/files')),
            ],
        ),
        migrations.CreateModel(
            name='Información',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(help_text='Título de la información', max_length=80)),
                ('contenido', models.TextField(help_text='Contenido de la información que va a mostrar el bot con algún comando vinculado')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del usuario en telegram autorizado a usar el bot', max_length=30)),
                ('usuario_telegram_id', models.CharField(help_text='ID del usuario en telegram autorizado a usar el bot', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Configuración',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_telegram', models.ManyToManyField(to='bot.usuariotelegram')),
            ],
        ),
        migrations.CreateModel(
            name='Comando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del Documento', max_length=30)),
                ('descripción', models.CharField(default='Sin descripción', help_text='Descripción del comando a mostrar en la ayuda del bot', max_length=120)),
                ('documento', models.OneToOneField(blank=True, help_text='Documento que va a retornar el bot con el comando', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bot.documento')),
                ('información', models.OneToOneField(blank=True, help_text='Texto que va a mostrar el bot con el comando (sí no se establece un documento)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bot.información')),
            ],
        ),
    ]
