# Generated by Django 4.1.1 on 2022-10-03 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comando',
            name='documento',
            field=models.OneToOneField(blank=True, help_text='Documento que va a retornar el bot con el comando', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.documento'),
        ),
    ]
